name: dart_flight
version: 0.1.1
author: Stefan Nolde
description: A simple IOC framework with future project pattern support in mind.
homepage: https://github.com/snolde/dart_flight
environment:
  sdk: '>=0.5.5'

#dependencies:
#  unittest: any